spring:
  datasource:
    url: jdbc:mysql://localhost:3306/testdb?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: user01
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver


  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    generate-ddl: false
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto:
      implicit_naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
      physical_naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    properties:
      hibernate:
        show_sql: false
        format_sql: false
        use_sql_comments: false
        #type: trace


logging:
  level:
    org.hibernate.SQL: debug

